Fix #376 --path option of install cli not working as expected
projectatomic/vagrant-service-manager pull request #416
Opened 2016-10-19 09:10 UTC by budhrg

Fix #376

* install-cli command will fail if invalid --path is given or
  path needs permission

2016-10-19 09:31 UTC, budhrg commented
@hferentschik CI is passing :+1:

2016-10-19 11:52 UTC, hferentschik commented on features/install-cli.feature
> +    And stderr from evaluating and running "bundle exec vagrant service-manager install-cli docker --path #{ENV['VAGRANT_HOME']}/unknown_dir/docker" should match /Directory path #{ENV['VAGRANT_HOME']
Nice 👍

2016-10-19 11:52 UTC, hferentschik commented on features/install-cli.feature
> +    And stderr from evaluating and running "bundle exec vagrant service-manager install-cli docker --path #{ENV['VAGRANT_HOME']}/unknown_dir/docker" should match /Directory path #{ENV['VAGRANT_HOME']
What's about testing/verifying that the error message in the original bug report is not in the output? Neither here, nor in any of the successful cases of install-cli

2016-10-20 14:32 UTC, budhrg commented
retest this please

2016-10-20 15:06 UTC, budhrg commented
@hferentschik The tests seems to be passing now. This time sure :smile: However, there is one testcase which is failing in terms of openshift
`bundle exec vagrant service-manager install-cli openshift` which I don't know. I tried a lot for its debugging.

However, its cli-version `bundle exec vagrant service-manager install-cli openshift --cli-version 1.3.1` is passing.
This PR has --cli-version.

The failed one is here https://ci.centos.org/job/vagrant-service-manager-budh/11/console.

However, no such issue in case of `cdk-openshift.feature` (https://github.com/budhrg/vagrant-service-manager/blob/e81d07a3e4b73042a1f633391318696e6e7750f0/features/cdk-openshift.feature).

I believe if you have not any other review, we can merge it and investigate the edge case in this issue https://github.com/projectatomic/vagrant-service-manager/issues/415

Let me know what is your opinion.

2016-10-20 16:44 UTC, budhrg commented
retest this please

2016-10-20 19:20 UTC, hferentschik requested changes
Getting there. Looking quite good now. Not quite sure what to think about 20 seconds timeout. Does it really have to be so high. We also needs to get to the bottom of this from a CDK side of things. There should be no wait required really. 

For me to get through the test suite, I still need https://github.com/hferentschik/vagrant-service-manager/commit/19cf82481a843d9f4e16ad6421bcb3dde1132028

2016-10-20 19:20 UTC, hferentschik commented on features/adb-openshift.feature
> +    When I successfully run `sleep 20`
That's a pretty long timeout. Really imo this also an issue of the underlying service setup. I expect that when Vagrant up has completed, everything is up and running, but you seem to imply this is not the case.

2016-10-20 19:20 UTC, hferentschik commented on features/adb-openshift.feature
> +    When I successfully run `bundle exec vagrant service-manager status`
"And I sucessfully" ...

2016-10-20 19:20 UTC, hferentschik commented on features/adb-openshift.feature
> +    When I successfully run `sleep 20`
Do you have an idea why this is necessary?

2016-10-20 19:20 UTC, hferentschik commented on features/adb-openshift.feature
> +    When I successfully run `sleep 20`
Also, I think we are better of to create our own step definition. Something like "When I sleep 20 seconds". Then in the implementation you are calling Ruby's sleep method. This way you are doing things within Ruby. Using `sleep 2-` effectively calls the shells sleep command which might or might not work on Windows.

2016-10-20 19:20 UTC, hferentschik commented on features/adb-openshift.feature
> +    And stdout from "bundle exec vagrant service-manager install-cli openshift --cli-version 1.3.0 --path #{ENV['VAGRANT_HOME']}/oc" should be evaluable in a shell
👍

2016-10-20 19:20 UTC, hferentschik commented on features/cdk-openshift.feature
> +    ==> default: Docker service configured successfully...
👍

2016-10-20 19:20 UTC, hferentschik commented on features/install-cli.feature
> +    And stderr from evaluating and running "bundle exec vagrant service-manager install-cli docker --path #{ENV['VAGRANT_HOME']}/unknown_dir/docker" should match /Directory path #{ENV['VAGRANT_HOME']
👍

2016-10-20 19:20 UTC, hferentschik commented on features/support/env.rb
> +Then(%r{^stderr from evaluating and running "([^"]*)" should match /(.*)/$}) do |cmd, regexp|
:-)

2016-10-20 19:20 UTC, hferentschik commented on lib/vagrant-service-manager/installer.rb
> +        msg = ''
Is this to handle the right output for the 'eval'?

2016-10-20 19:21 UTC, hferentschik commented
retest

2016-10-20 19:32 UTC, hferentschik commented
retest

2016-10-20 19:33 UTC, hferentschik commented
test this please

2016-10-21 02:03 UTC, budhrg commented on lib/vagrant-service-manager/installer.rb
> +        msg = ''
@hferentschik Yes

2016-10-21 04:12 UTC, budhrg commented
@hferentschik Hi, I have updated the tests now. It include both evalauable the install-cli command and added step for sleep too.

2016-10-21 05:03 UTC, budhrg commented
retest this please

2016-10-21 07:40 UTC, hferentschik commented
test this please

2016-10-21 07:55 UTC, hferentschik commented
@budhrg Did you create an issue somewhere in adb to find out why we need a wait period before between 'vagrant up' and the service-manager 'status'? That does not seem right to me. 

Also, lets create a follow up issue in service-manager to find a more direct condition than sleeping 10 seconds. This might or might not work depending on the machine the tests are running. It could be something like "And wait max x seconds to OpenShift to be operational" where the implementation checks in a loop some condition of the OpenShift cluster and times out after max seconds. Adding random waits to a test is a bad smell.

2016-10-21 07:56 UTC, hferentschik commented
@budhrg - does this `bundle exec rake clean features BOX=adb,cdk` pass all tests on your work station?

2016-10-21 08:03 UTC, hferentschik commented
@budhrg Didn't we want to enable the Kubernates features on CI as well?

2016-10-21 08:07 UTC, hferentschik requested changes
The tests are not passing! You need to convert the captured string into an int to make the sleep work.

```
      can't convert String into time interval (TypeError)
  /root/vagrant-service-manager/feature/support/env.rb:188:in `sleep'
```

2016-10-21 08:07 UTC, hferentschik commented on features/adb-openshift.feature
> +
Why don't you add the virtualbox memory settings here as well?

2016-10-21 08:17 UTC, hferentschik commented
@budhrg For what it's worth `bundle exec rake clean features BOX=adb,cdk` seems to work for me now ignoring the string conversion error (note this in itself makes of course all adb tests to be skipped)

2016-10-21 10:29 UTC, LalatenduMohanty commented on features/adb-openshift.feature
> +    When I sleep for 10 seconds
This should not be the case. We need to investigate the root cause of why we need 10s delay.

2016-10-21 11:46 UTC, hferentschik approved these changes
:+1

2016-10-21 11:49 UTC, merged