Fix #362 Adding OpenShift configuration options into VSM Readme
projectatomic/vagrant-service-manager pull request #437
Opened 2016-11-04 07:43 UTC by Preeticp

Adding a new section for Configuring Services.

2016-11-04 13:36 UTC, hferentschik requested changes
Looking good, except for the 'openshift_docker_registry' option which should be listed somehow separately as an option for customizing the Docker service.

2016-11-04 13:36 UTC, hferentschik commented on README.adoc
> +- `config.servicemanager.openshift_docker_registry = "docker.io"` - Specifies the registry from where the service should be pulled.
This is not related to OpenShift afaik. This is really a Docker service configuration option. To use a custom OpenShift version you need 'openshift_image_name' and 'openshift_image_tag'. @budhrg, correct?

@Preeticp Any chance you actually tested this? Is this still working end to end?

2016-11-04 13:36 UTC, hferentschik commented on README.adoc
> +- `config.servicemanager.openshift_image_tag = "v1.2.0"` - Specifies the version of the image to be used.
maybe 1.3.0 instead of 1.2.0 ( a bit more recent)

2016-11-06 13:34 UTC, budhrg commented on README.adoc
> +- `config.servicemanager.openshift_image_tag = "v1.2.0"` - Specifies the version of the image to be used.
@Preeticp yes we can change to 1.3.0

2016-11-07 05:14 UTC, praveenkumar commented on README.adoc
> +- `config.servicemanager.openshift_docker_registry = "docker.io"` - Specifies the registry from where the service should be pulled.
@hferentschik it is related to openshift if openshift images are coming from different hub than `docker.io` like for our CDK it's from `access.redhat.com` and if someone have private registry which contain those images then using that registry.

2016-11-07 08:40 UTC, hferentschik commented on README.adoc
> +- `config.servicemanager.openshift_docker_registry = "docker.io"` - Specifies the registry from where the service should be pulled.
@praveenkumar, ok, it might be worth to elaborate on this a bit though.
@praveenkumar does this registry setting only apply for the OpenShift image? I would not think so, right? Is this option just a away to add an additional registry? Can you specify more than one?

Another thing,
"from where the service should be pulled." => "from where the _OpenShift image_ is pulled."

2016-11-07 08:47 UTC, praveenkumar commented on README.adoc
> +- `config.servicemanager.openshift_docker_registry = "docker.io"` - Specifies the registry from where the service should be pulled.
> does this registry setting only apply for the OpenShift image? 

yes that's right.

> I would not think so, right? Is this option just a away to add an additional registry?

No to add another registry to docker we have different script https://github.com/projectatomic/adb-utils/blob/master/utils/add_insecure_registry.

this option is for "where OpenShift image pulled from".

2016-11-07 12:56 UTC, hferentschik approved these changes

2016-11-07 12:58 UTC, merged